version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "40000-40099:40000-40099"  # WebRTC ports
    environment:
      - NODE_ENV=production
      - MEDIASOUP_NUM_WORKERS=2
      - HTTP_LISTEN_PORT=3000
      - HTTP_LISTEN_IP=0.0.0.0
      - DOMAIN=localhost
      - WEBRTC_LISTEN_IP=0.0.0.0
      - WEBRTC_INITIAL_AVAILABLE_PORT=40000
      - ANNOUNCED_IP=127.0.0.1
    volumes:
      - ./server/.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - server
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - server
      - client
    restart: unless-stopped
